### ISSUE TITLE
IP address changes do not apply until module is restarted

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/driver#14]
When changing an instance's IP addresses, this does not trigger a reconnect of the transport to the new host.

I'm assuming that an `on_update` callback _may_ fire (untested), which could be used to detect this and force a reconnect. However, this appears to be something that is more suited to the responsibilities of the driver framework itself.

**Comment by stakach** [comment]
@caspiano I was thinking that this should occur at the `core` level as technically a start and stop is required.

What are your thoughts?
Basically was thinking any changes to `ip`, `port`, `tls`, `udp`, `makebreak`, `uri` should result in core requesting the module stop and then start again. If none of those fields changed then it performs the `update` request

**Comment by stakach** [comment]
Our other option is to do it as part of the [driver update](https://github.com/PlaceOS/driver/blob/016c023c5f4528a1e9faa4381e0a192674c9639a/src/driver/driver_manager.cr#L116)

but thinking core has the information about the changes?
otherwise probably not hard to perform the action in the link above

**Comment by caspiano** [comment]
should be simple enough to do at the core level
